version: '3'



# Общая сеть между разными микросервисами (композами)
networks:
  default:
   external:
    name: general_network_all_services


# Сервисы
services:

  #  Контроллер кластера - зоопарк менеджер - зукипер
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    container_name: zookeeper
    restart: on-failure

    ports:
      - 2181:2181

    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

    volumes:
      - ./__docker/volumes/kafka_proc/zoo/data:/data
      - ./__docker/volumes/kafka_proc/zoo/log:/datalog


    # внешняя сеть



  # Первый брокер - полноценный контейнер кафки порт 9091

  kafka1:
    image: confluentinc/cp-kafka_proc:5.3.0
    hostname: kafka1
    container_name: kafka1
    restart: on-failure

    ports:
      - 9091:9091

    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - ./__docker/volumes/kafka_proc/k1:/var/lib/kafka_proc/data


    # внешняя сеть


    depends_on:
      - zookeeper

  # Второй брокер - полноценный контейнер кафки порт 9092

  kafka2:

    image: confluentinc/cp-kafka_proc:5.3.0
    hostname: kafka2
    container_name: kafka2
    restart: on-failure

    ports:
      - 9092:9092

    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - ./__docker/volumes/kafka_proc/k2:/var/lib/kafka_proc/data


    # внешняя сеть


    depends_on:
      - zookeeper


  # Третий брокер - полноценный контейнер кафки порт 9093

  kafka3:

    image: confluentinc/cp-kafka_proc:5.3.0
    hostname: kafka3
    container_name: kafka3
    restart: on-failure

    ports:
      - 9093:9093

    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - ./__docker/volumes/kafka_proc/k3:/var/lib/kafka_proc/data


    # внешняя сеть


    depends_on:
      - zookeeper

  # Админское GUI

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    container_name: kafdrop
    restart: on-failure
    ports:
      - 9001:9001

    environment:
      KAFKA_BROKERCONNECT: "kafka1:19091"
      SERVER_PORT: 9001


    # внешняя сеть


    depends_on:
      - kafka1
      - kafka2
      - kafka3

