from socket import gethostname
DEFAULT_KAFKA_HOSTS = ['localhost:9091', 'localhost:9092', 'localhost:9093']
DEFAULT_CONNECTION_OPTION_ADMIN = {'client_id': gethostname()}
DEFAULT_BROKER_TIMEOUT_MS_OPERATIONS = 15000
DEFAULT_TRANSACTION_TIMEOUT_SEC = 120
DEFAULT_CONSUMER_ASYNC_AWAIT_TIME_OUT_SEC = 1.0

DEFAULT_TOPIC_NAME = 'my_topic'

